cart/urls.py
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('add/<int:pk>', views.AddCart.as_view(), name="add"),
    # path('update/<int:pk>', views.UpdateCart.as_view(), name="update"),
    path('delete/<int:pk>', views.DeleteCart.as_view(), name="delete"),
]

compare/urls.py
from django.urls import path
from . import views

app_name = "compare"
urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('add/<int:pk>', views.AddCompare.as_view(), name="add"),
    path('delete/<int:pk>', views.DeleteCompare.as_view(), name="delete"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include("shop.urls")),
    path('cart/', include('cart.urls')),
    path('compare/', include('compare.urls')),
    path('admin/', admin.site.urls),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"
urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('product/<int:pk>/', views.ProductDetail.as_view(), name='detail'), #<int:pk>
    path('checkout/', views.checkout),
    path('store/', views.store, name="store"),
]

shop/models.py
from django.db import models
from mptt import models as mpttmodels
from django.utils.text import slugify
import os
from django.contrib.auth.models import AbstractUser
from django.conf import settings
import time 
  

class User(AbstractUser):
    birth_date = models.DateField(null=True, blank=True)
    phone_Number = models.CharField(max_length=11)
    addresses = models.TextField()
    updated_at =  models.DateField(auto_now=True)


def get_upload_path(instance, filename):
    if hasattr(instance,'category'):
        tmp = os.path.join('images', str(instance.category),str(instance.name),filename)
        return tmp
    elif hasattr(instance,'parent'):
        tmp = os.path.join('images','category',filename)
        return tmp
    else:
        tmp = os.path.join('images','brand',filename)
        return tmp

# Create your models here.
class Category(mpttmodels.MPTTModel):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to=get_upload_path)
    parent = mpttmodels.TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    def __str__(self):
        return self.name
    
class Brand(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to=get_upload_path)
    def __str__(self):
        return self.name
    
class Property(models.Model):
    key = models.CharField(max_length=50)
    value = models.CharField(max_length=300)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Properties"

    def __str__(self):
        return self.key + ":" + self.value


class Product(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, unique=True)
    brand = models.ForeignKey(Brand, on_delete=models.SET_DEFAULT, default="No Brand")
    specification = models.ManyToManyField(Property)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    long_description = models.TextField()
    short_description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default="No Category")
    number_of_sold = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField()
    image1 = models.ImageField(upload_to=get_upload_path)
    image2 = models.ImageField(upload_to=get_upload_path, null=True, blank=True)
    image3 = models.ImageField(upload_to=get_upload_path, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name


class Promotions(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,)
    start_Date = models.DateTimeField()
    end_Date = models.DateTimeField()
    percentage = models.IntegerField()

    def __str__(self):
        return self.product.product.name + " OFF! -->" + str(self.percentage)


class Reviews(models.Model):

    class RT(models.IntegerChoices):
        ONE = 1
        TWO = 2
        THREE = 3
        FOUR = 4
        FIVE = 5

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rating = models.IntegerField(choices = RT.choices)

class Favorites(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)



class Order(models.Model):

    class StatusChoice(models.TextChoices):
        PENDING = 'P', 'Pending'
        SUCCESFUL = 'S', 'Succesful'
        CANCELED = 'C', 'Canceled'
        
    product = models.ManyToManyField(Product,through='OrderItems')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    total_quantity = models.IntegerField()
    total_cost = models.DecimalField(decimal_places=2, max_digits=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at =  models.DateField(auto_now=True)
    status = models.CharField(max_length=1,choices=StatusChoice.choices, default=StatusChoice.PENDING)
    description = models.TextField()


class OrderItems(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    unit_cost = models.DecimalField(decimal_places=2, max_digits=10)
    total_product_cost = models.DecimalField(decimal_places=2, max_digits=10)

    def save(self, *args, **kwargs):
        self.unit_cost = self.quantity * self.unit_cost
        super(OrderItems, self).save(*args, **kwargs)

shop/views.py
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render
from django.views import View
from shop.models import Product, Order, Reviews, Category, Promotions, Favorites, Brand
from django.views.generic import DetailView

# Create your views here.
#              #            1-parent categories Category.objects.filter(parent__isnull=True)
#              #            2-new product (by category) Product.objects.filter(category=Category.objects.get(id=6)).order_by('created_at')[:10]
#              #            3-hot deal     --> image                      
#              #            4-top selling (by category)
#              #            5-top brand distinct("brand")
#                           6-top best selling product prod = Product.objects.annotate(num_orders=Count('order')).order_by('num_orders')[:10]
#
class Index(View): 
    def get(self,request):
        if request.GET.get('id'):
            id = request.GET.get('id')
            _product = Product.objects.get(pk=id)
            product=dict()
            product["name"] = _product.name
            product["price"] = _product.price
            product["short_description"] = _product.short_description
            product["image"] = _product.image1.url
            return JsonResponse(product)
        categories = Category.objects.filter(parent__isnull=True)
        newProducts = {}
        topSellings = {}
        for category in categories:
          newProducts[category.name] = Product.objects.filter(category=category.id).order_by('-created_at')[:5]
          topSellings[category.name] = Product.objects.filter(category=category.id).order_by('-number_of_sold')[:5]
        topBrand = Brand.objects.all().order_by('-product__number_of_sold')[:4]
        
        template_name = "index.html"
        context = {
            'topBrands': topBrand,
            'newProducts': newProducts,
            'categories': categories,
            'topSellings': topSellings,
            }
        return render(request,template_name,context,)
    



class ProductDetail(View):
    def get(self,request, pk):
        template_name = "product.html"
        product = Product.objects.get(pk=pk)
        categories = Category.objects.get(pk=product.category.id).get_family()
        relatedP = Product.objects.filter(category=product.category).exclude(pk=pk)[:5]
        context = {
            'product':product,
            'categories':categories,
            'relatedP': relatedP
            }
        return render(request,template_name,context,)

def product(request):
    template_name = "product.html"
    return render(request,template_name)

def checkout(request):
    template_name = "checkout.html"
    return render(request,template_name)

def store(request):
    template_name = "store.html"
    return render(request,template_name)

shop/templates/base.html
{% load static %}
{% load mathfilters %}
<!DOCTYPE html>

   	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>
        {% block title %}
        {% endblock title %}
        </title>

		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href=" {% static 'shop/css/bootstrap.min.css' %} "/>

		<!-- Slick -->
		<link type="text/css" rel="stylesheet" href=" {% static 'shop/css/slick.css' %} "/>
		<link type="text/css" rel="stylesheet" href="{% static 'shop/css/slick-theme.css' %} "/>

		<!-- nouislider -->
		<link type="text/css" rel="stylesheet" href=" {% static 'shop/css/nouislider.min.css' %} "/>

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href=" {% static 'shop/css/font-awesome.min.css' %} ">

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href="{% static 'shop/css/style.css' %} "/>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

    </head>
    <body>
    <!-- HEADER -->
		<header>
			<!-- TOP HEADER -->
			<div id="top-header">
				<div class="container">
					<ul class="header-links pull-left">
						<li><a href="#"><i class="fa fa-phone"></i> +98-910-913-94-90</a></li>
						<li><a href="#"><i class="fa fa-envelope-o"></i> a9473m@gmail.com</a></li>
						<li><a href="#"><i class="fa fa-map-marker"></i> Tehran - Iran</a></li>
					</ul>
					<ul class="header-links pull-right">
						<li><a href="#"><i class="fa fa-dollar"></i> USD</a></li>
						<li><a href="#"><i class="fa fa-user-o"></i> My Account</a></li>
					</ul>
				</div>
			</div>
			<!-- /TOP HEADER -->

			<!-- MAIN HEADER -->
			<div id="header">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<!-- LOGO -->
						<div class="col-md-2">
							<div class="header-logo">
								<a href="{% url 'shop:index' %}" class="logo">
									<img src=" {% static 'shop/img/logo.png' %} " alt="">
								</a>
							</div>
						</div>
						<!-- /LOGO -->

						<!-- SEARCH BAR -->
						<div class="col-md-6">
							<div class="header-search">
								<form method="GET" action="{% url 'shop:store' %}">
									<select class="input-select" name="category">
										<option value="0">All Categories</option>
										{% for category in categories %}
											<option value={{category.id}}>{{ category.name}}</option>
										{% endfor %}
									</select>
									<input class="input" placeholder="Search here" name="search">
									<button type=submit class="search-btn">Search</button>
								</form>
							</div>
						</div>
						<!-- /SEARCH BAR -->

						<!-- ACCOUNT -->
						<div class="col-md-4 clearfix">
							<div class="header-ctn">
								<!-- Wishlist -->
								<div>
									<a href="#">
										<i class="fa fa-heart-o"></i>
										<span>Your Wishlist</span>
										<div class="qty">2</div>
									</a>
								</div>
								<!-- /Wishlist -->

								<div class="dropdown">
									<a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
										<i class="fa fa-exchange"></i>
										<span>Your Compare</span>
										<div class="qty">{{compare|length}}</div>
									</a>
									<div class="cart-dropdown">
										<div class="cart-list">
										{% for item in compare %}
											<div class="product-widget">
												<div class="product-img">
													<img src="{{item.product.image1.url}}" alt="">
												</div>
												<div class="product-body">
													<h3 class="product-name"><a href="{% url 'shop:detail' item.product.id %}">{{item.product.name}}</a></h3>
													<h4 class="product-price"> $ {{item.product.price}}</h4>
												</div>
												          <form method="POST" action="{% url 'compare:delete' item.product.id %}">
															{% csrf_token %}
														<button class="delete"><i class="fa fa-close"></i></button>
														</form>
											</div>
										{% endfor %}
										</div>
										<div class="cart-btns">
											<a href="{% url 'compare:index' %}">View Items in Comparing Section</a>
										</div>
									</div>
								</div>
								<!-- Cart -->
								<div class="dropdown">
									<a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
										<i class="fa fa-shopping-cart"></i>
										<span>Your Cart</span>
										<div class="qty">{{cart|length}}</div>
									</a>
									<div class="cart-dropdown">
										<div class="cart-list">
										{% for item in cart %}
											<div class="product-widget">
												<div class="product-img">
													<img src="{{item.product.image1.url}}" alt="">
												</div>
												<div class="product-body">
													<h3 class="product-name"><a href="{% url 'shop:detail' item.product.id %}">{{item.product.name}}</a></h3>
													<h4 class="product-price"><span class="qty">{{item.quantity}}x</span>$ {{item.product.price}}</h4>
												</div>
												          <form method="POST" action="{% url 'cart:delete' item.product.id %}">
															{% csrf_token %}
														<button class="delete"><i class="fa fa-close"></i></button>
														</form>
											</div>
										{% endfor %}
										</div>
										<div class="cart-summary">
											<small>3 Item(s) selected</small>
											<h5>SUBTOTAL: $2940.00</h5>
										</div>
										<div class="cart-btns">
											<a href="{% url 'cart:index' %}">View Cart</a>
											<a href="#">Checkout  <i class="fa fa-arrow-circle-right"></i></a>
										</div>
									</div>
								</div>
								<!-- /Cart -->

								<!-- Menu Toogle -->
								<div class="menu-toggle">
									<a href="#">
										<i class="fa fa-bars"></i>
										<span>Menu</span>
									</a>
								</div>
								<!-- /Menu Toogle -->
							</div>
						</div>
						<!-- /ACCOUNT -->
					</div>
					<!-- row -->
				</div>
				<!-- container -->
			</div>
			<!-- /MAIN HEADER -->
		</header>
		<!-- /HEADER -->

		<!-- NAVIGATION -->
		<nav id="navigation">
			<!-- container -->
			<div class="container">
				<!-- responsive-nav -->
				<div id="responsive-nav">
					<!-- NAV -->
					<ul class="main-nav nav navbar-nav">
						<li class="active"><a href="#">Home</a></li>
						<li><a href="#">Hot Deals</a></li>
						{% for category in categories %}
							<li><a href="#">{{ category.name}}</a></li>
						{% endfor %}
						

					</ul>
					<!-- /NAV -->
				</div>
				<!-- /responsive-nav -->
			</div>
			<!-- /container -->
		</nav>
		<!-- /NAVIGATION -->

        {% block content %}
        {% endblock content %}
<!-- NEWSLETTER -->
		<div id="newsletter" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<div class="newsletter">
							<p>Sign Up for the <strong>NEWSLETTER</strong></p>
							<form>
								<input class="input" type="email" placeholder="Enter Your Email">
								<button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
							</form>
							<ul class="newsletter-follow">
								<li>
									<a href="#"><i class="fa fa-facebook"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-twitter"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-instagram"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-pinterest"></i></a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /NEWSLETTER -->
		<!-- FOOTER -->
		<footer id="footer">
			<!-- top footer -->
			<div class="section">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">About Us</h3>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
								<ul class="footer-links">
									<li><a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
									<li><a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
									<li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Categories</h3>
								<ul class="footer-links">
									<li><a href="#">Hot deals</a></li>
									<li><a href="#">Laptops</a></li>
									<li><a href="#">Smartphones</a></li>
									<li><a href="#">Cameras</a></li>
									<li><a href="#">Accessories</a></li>
								</ul>
							</div>
						</div>

						<div class="clearfix visible-xs"></div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Information</h3>
								<ul class="footer-links">
									<li><a href="#">About Us</a></li>
									<li><a href="#">Contact Us</a></li>
									<li><a href="#">Privacy Policy</a></li>
									<li><a href="#">Orders and Returns</a></li>
									<li><a href="#">Terms & Conditions</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Service</h3>
								<ul class="footer-links">
									<li><a href="#">My Account</a></li>
									<li><a href="#">View Cart</a></li>
									<li><a href="#">Wishlist</a></li>
									<li><a href="#">Track My Order</a></li>
									<li><a href="#">Help</a></li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /top footer -->

			<!-- bottom footer -->
			<div id="bottom-footer" class="section">
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-12 text-center">
							<ul class="footer-payments">
								<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
								<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
							</ul>
							<span class="copyright">
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</span>
						</div>
					</div>
						<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /bottom footer -->
		</footer>
		<!-- /FOOTER -->

		<!-- jQuery Plugins -->
		<script src=" {% static 'shop/js/jquery.min.js' %} "></script>
		<script src=" {% static 'shop/js/bootstrap.min.js' %} "></script>
		<script src=" {% static 'shop/js/slick.min.js' %} "></script>
		<script src=" {% static 'shop/js/nouislider.min.js' %} "></script>
		<script src=" {% static 'shop/js/jquery.zoom.min.js' %} "></script>
		<script src=" {% static 'shop/js/main.js' %} "></script>
		<script src=" {% static 'shop/js/myscript.js' %} "></script>

    </body>
</html>

shop/templates/checkout.html
{% extends 'templates/base.html' %}
{% load static %}

		{% block title %}
		Checkout
		{% endblock title %}

{% block content %}
		<!-- BREADCRUMB -->
		<div id="breadcrumb" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<h3 class="breadcrumb-header">Checkout</h3>
						<ul class="breadcrumb-tree">
							<li><a href="#">Home</a></li>
							<li class="active">Checkout</li>
						</ul>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /BREADCRUMB -->

		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">

					<div class="col-md-7">
						<!-- Billing Details -->
						<div class="billing-details">
							<div class="section-title">
								<h3 class="title">Billing address</h3>
							</div>
							<div class="form-group">
								<input class="input" type="text" name="first-name" placeholder="First Name">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="last-name" placeholder="Last Name">
							</div>
							<div class="form-group">
								<input class="input" type="email" name="email" placeholder="Email">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="address" placeholder="Address">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="city" placeholder="City">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="country" placeholder="Country">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="zip-code" placeholder="ZIP Code">
							</div>
							<div class="form-group">
								<input class="input" type="tel" name="tel" placeholder="Telephone">
							</div>
							<div class="form-group">
								<div class="input-checkbox">
									<input type="checkbox" id="create-account">
									<label for="create-account">
										<span></span>
										Create Account?
									</label>
									<div class="caption">
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
										<input class="input" type="password" name="password" placeholder="Enter Your Password">
									</div>
								</div>
							</div>
						</div>
						<!-- /Billing Details -->

						<!-- Shiping Details -->
						<div class="shiping-details">
							<div class="section-title">
								<h3 class="title">Shiping address</h3>
							</div>
							<div class="input-checkbox">
								<input type="checkbox" id="shiping-address">
								<label for="shiping-address">
									<span></span>
									Ship to a diffrent address?
								</label>
								<div class="caption">
									<div class="form-group">
										<input class="input" type="text" name="first-name" placeholder="First Name">
									</div>
									<div class="form-group">
										<input class="input" type="text" name="last-name" placeholder="Last Name">
									</div>
									<div class="form-group">
										<input class="input" type="email" name="email" placeholder="Email">
									</div>
									<div class="form-group">
										<input class="input" type="text" name="address" placeholder="Address">
									</div>
									<div class="form-group">
										<input class="input" type="text" name="city" placeholder="City">
									</div>
									<div class="form-group">
										<input class="input" type="text" name="country" placeholder="Country">
									</div>
									<div class="form-group">
										<input class="input" type="text" name="zip-code" placeholder="ZIP Code">
									</div>
									<div class="form-group">
										<input class="input" type="tel" name="tel" placeholder="Telephone">
									</div>
								</div>
							</div>
						</div>
						<!-- /Shiping Details -->

						<!-- Order notes -->
						<div class="order-notes">
							<textarea class="input" placeholder="Order Notes"></textarea>
						</div>
						<!-- /Order notes -->
					</div>

					<!-- Order Details -->
					<div class="col-md-5 order-details">
						<div class="section-title text-center">
							<h3 class="title">Your Order</h3>
						</div>
						<div class="order-summary">
							<div class="order-col">
								<div><strong>PRODUCT</strong></div>
								<div><strong>TOTAL</strong></div>
							</div>
							<div class="order-products">
								<div class="order-col">
									<div>1x Product Name Goes Here</div>
									<div>$980.00</div>
								</div>
								<div class="order-col">
									<div>2x Product Name Goes Here</div>
									<div>$980.00</div>
								</div>
							</div>
							<div class="order-col">
								<div>Shiping</div>
								<div><strong>FREE</strong></div>
							</div>
							<div class="order-col">
								<div><strong>TOTAL</strong></div>
								<div><strong class="order-total">$2940.00</strong></div>
							</div>
						</div>
						<div class="payment-method">
							<div class="input-radio">
								<input type="radio" name="payment" id="payment-1">
								<label for="payment-1">
									<span></span>
									Direct Bank Transfer
								</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
								</div>
							</div>
							<div class="input-radio">
								<input type="radio" name="payment" id="payment-2">
								<label for="payment-2">
									<span></span>
									Cheque Payment
								</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
								</div>
							</div>
							<div class="input-radio">
								<input type="radio" name="payment" id="payment-3">
								<label for="payment-3">
									<span></span>
									Paypal System
								</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
								</div>
							</div>
						</div>
						<div class="input-checkbox">
							<input type="checkbox" id="terms">
							<label for="terms">
								<span></span>
								I've read and accept the <a href="#">terms & conditions</a>
							</label>
						</div>
						<a href="#" class="primary-btn order-submit">Place order</a>
					</div>
					<!-- /Order Details -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->

{% endblock content %}